export {
  manager,
  ClientConfig,
  ConfigOption,
  defaultConfig,
  newConfig,
  newConfigFromEnv,
  validateConfig,
  cloneConfig,
  mergeConfig,
  configToString,
  withEndpoint,
  withTimeout,
  withMaxRetries,
  withRetryDelay,
  withAPIKey,
  withUserAgent,
  withDebug,
  withLogLevel,
  withMaxConnections,
  withHeaders,
  DEFAULT_POLL_INTERVAL_MS,
} from './config';
